<?php
/**
 * Custom XML sitemaps: an index plus pages / celebrities / countries /
 * blog / versus children. Core sitemaps are disabled in inc/rewrites.php.
 *
 * @package HeightCompare
 */

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Intercept sitemap requests before core's canonical redirect (which would
 * otherwise bounce /sitemap.xml to the disabled /wp-sitemap.xml). Runs at
 * template_redirect priority 0, matching the request path directly so it is
 * independent of rewrite-rule timing.
 */
/**
 * Render the sitemap on template_redirect priority 1 — before core's
 * redirect_canonical (priority 10), which would otherwise bounce
 * /sitemap.xml to the disabled /wp-sitemap.xml. The hc_sitemap query var is
 * set deterministically by hc_force_sitemap_query() in inc/rewrites.php.
 */
function hc_render_sitemap_early(): void {
	$name = get_query_var( 'hc_sitemap' );
	if ( is_string( $name ) && '' !== $name ) {
		hc_render_sitemap( $name ); // Exits.
	}
}
add_action( 'template_redirect', 'hc_render_sitemap_early', 1 );

/**
 * Render a sitemap and exit.
 *
 * @param string $name index|pages|celebrities|countries|blog|versus.
 */
function hc_render_sitemap( string $name ): void {
	header( 'Content-Type: application/xml; charset=UTF-8' );
	header( 'X-Robots-Tag: noindex, follow', true );
	echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";

	if ( 'index' === $name ) {
		hc_render_sitemap_index();
	} else {
		hc_render_sitemap_urlset( $name );
	}
	exit;
}

/**
 * Sitemap index listing the child sitemaps.
 */
function hc_render_sitemap_index(): void {
	$children = array( 'pages', 'celebrities', 'countries', 'blog', 'versus' );
	echo '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
	foreach ( $children as $child ) {
		printf(
			"<sitemap><loc>%s</loc></sitemap>\n",
			esc_url( home_url( '/sitemap-' . $child . '.xml' ) )
		);
	}
	echo '</sitemapindex>';
}

/**
 * Render a <urlset> for a given child sitemap.
 *
 * @param string $name Child name.
 */
function hc_render_sitemap_urlset( string $name ): void {
	echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
	foreach ( hc_sitemap_urls( $name ) as $url ) {
		printf(
			"<url><loc>%s</loc>%s</url>\n",
			esc_url( $url['loc'] ),
			'' !== $url['lastmod'] ? '<lastmod>' . esc_html( $url['lastmod'] ) . '</lastmod>' : ''
		);
	}
	echo '</urlset>';
}

/**
 * URLs for a child sitemap.
 *
 * @param string $name Child name.
 * @return array<int, array{loc: string, lastmod: string}>
 */
function hc_sitemap_urls( string $name ): array {
	$urls = array();

	switch ( $name ) {
		case 'pages':
			$urls[] = array( 'loc' => home_url( '/' ), 'lastmod' => '' );
			foreach ( array( 'height-chart', 'height-converter' ) as $slug ) {
				$page = get_page_by_path( $slug );
				if ( $page instanceof WP_Post ) {
					$urls[] = array(
						'loc'     => (string) get_permalink( $page ),
						'lastmod' => get_post_modified_time( 'c', true, $page ) ?: '',
					);
				}
			}
			$urls[] = array( 'loc' => (string) get_post_type_archive_link( 'celebrity' ), 'lastmod' => '' );
			break;

		case 'celebrities':
			$urls = hc_sitemap_posts( 'celebrity' );
			break;

		case 'countries':
			$urls = hc_sitemap_posts( 'country_average' );
			break;

		case 'blog':
			$urls = hc_sitemap_posts( 'post' );
			break;

		case 'versus':
			$urls = hc_sitemap_versus();
			break;
	}

	return $urls;
}

/**
 * URLs for a post type.
 *
 * @param string $post_type Post type.
 * @return array<int, array{loc: string, lastmod: string}>
 */
function hc_sitemap_posts( string $post_type ): array {
	$posts = get_posts(
		array(
			'post_type'      => $post_type,
			'post_status'    => 'publish',
			'posts_per_page' => 5000,
			'orderby'        => 'modified',
			'order'          => 'DESC',
		)
	);
	$urls = array();
	foreach ( $posts as $post ) {
		$urls[] = array(
			'loc'     => (string) get_permalink( $post ),
			'lastmod' => get_post_modified_time( 'c', true, $post ) ?: '',
		);
	}
	return $urls;
}

/**
 * Top versus URLs, crawl-budget aware: only indexable pairs (both ≥ 100
 * search volume). Generated by pairing high-volume celebrities.
 *
 * @return array<int, array{loc: string, lastmod: string}>
 */
function hc_sitemap_versus(): array {
	$celebs = get_posts(
		array(
			'post_type'      => 'celebrity',
			'post_status'    => 'publish',
			'posts_per_page' => 40,
			'meta_key'       => 'hc_search_volume',
			'orderby'        => 'meta_value_num',
			'order'          => 'DESC',
			'meta_query'     => array(
				array(
					'key'     => 'hc_search_volume',
					'value'   => 100,
					'compare' => '>=',
					'type'    => 'NUMERIC',
				),
			),
		)
	);

	$urls  = array();
	$count = count( $celebs );
	for ( $i = 0; $i < $count; $i++ ) {
		for ( $j = $i + 1; $j < $count; $j++ ) {
			$slug_a = str_replace( '-height', '', $celebs[ $i ]->post_name );
			$slug_b = str_replace( '-height', '', $celebs[ $j ]->post_name );
			$urls[] = array(
				'loc'     => hc_versus_url( $slug_a . '-vs-' . $slug_b ),
				'lastmod' => '',
			);
			if ( count( $urls ) >= 500 ) {
				return $urls;
			}
		}
	}
	return $urls;
}

/**
 * Advertise the sitemap in robots.txt.
 *
 * @param string $output Robots content.
 * @return string
 */
function hc_robots_txt( string $output ): string {
	$output .= "\nSitemap: " . home_url( '/sitemap.xml' ) . "\n";
	return $output;
}
add_filter( 'robots_txt', 'hc_robots_txt' );
